#	$Id: Makefile.bsd,v 1.3 2001/11/25 21:09:38 ragge Exp $
#
UNAME!= uname

.if $(UNAME) != Darwin
FLAGS="XFLAGS=-DSTAR_BSD -DREGEX"
LIBS="XLIBS=-ltermcap"
.else
BACKEND_EXTRA_OBJS="EXTRA_OBJS=poll_emul.o"
FLAGS="XFLAGS=-DSTAR_BSD -DREGEX -DPOLL_EMUL -DMACOSX"
.endif


all:
	@(cd backend; $(MAKE) $(FLAGS) $(BACKEND_EXTRA_OBJS))
	@(cd libredit; $(MAKE) $(FLAGS))
	@(cd rkom; $(MAKE) $(FLAGS) $(LIBS))

clean:
	@(cd backend; $(MAKE) clean)
	@(cd libredit; $(MAKE) clean)
	@(cd rkom; $(MAKE) clean)
