#      $Id: Makefile.linux,v 1.2 2001/11/22 21:30:53 ragge Exp $
#

FLAGS="XFLAGS=-DLINUX -DREGEX" CC=gcc
LIBS="XLIBS=-ltermcap"

all:
	@(cd backend; make $(FLAGS))
	@(cd libredit; make $(FLAGS))
	@(cd rkom; make $(FLAGS) $(LIBS))

clean:
	@(cd backend; make clean)
	@(cd libredit; make clean)
	@(cd rkom; make clean)

