#      $Id: Makefile.linux,v 1.1 2001/11/20 22:24:46 ragge Exp $
#

FLAGS="XFLAGS=-DLINUX -DREGEX -D_XPG4_2" CC=gcc
LIBS="XLIBS=-ltermcap -lnsl"

all:
	@(cd backend; make $(FLAGS))
	@(cd libredit; make $(FLAGS))
	@(cd rkom; make $(FLAGS) $(LIBS))

clean:
	@(cd backend; make clean)
	@(cd libredit; make clean)
	@(cd rkom; make clean)

