#	$Id: Makefile.solaris,v 1.1 2001/11/18 18:06:08 ragge Exp $
#

FLAGS="XFLAGS=-DSOLARIS -DREGEX -D_XPG4_2 -I../support" CC=gcc
LIBS="XLIBS=-ltermcap -lsocket -lnsl"

all:
	@(cd backend; make $(FLAGS))
	@(cd libredit; make $(FLAGS))
	@(cd rkom; make $(FLAGS) $(LIBS))

clean:
	@(cd backend; make clean)
	@(cd libredit; make clean)
	@(cd rkom; make clean)
