#	$Id: Makefile.solaris,v 1.4 2001/11/24 12:52:29 ragge Exp $
#

FLAGS="XFLAGS=-DSOLARIS -DREGEX" CC=gcc
LIBS="XLIBS=-ltermcap -lsocket -lnsl"

all:
	@(cd backend; make $(FLAGS))
	@(cd libredit; make $(FLAGS))
	@(cd rkom; make $(FLAGS) $(LIBS))

clean:
	@(cd backend; make clean)
	@(cd libredit; make clean)
	@(cd rkom; make clean)
