#	$Id: Makefile,v 1.2 2000/10/01 14:10:41 ragge Exp $
#
# Rkom backend library Makefile
#

LIB=	rkom
SRCS=	rkom_subr.c rkom_lyskom.c rkom_be.c rkom_beparse.c rkom_conf.c \
	rkom_helpers.c

MKLINT=	no	# No lint library
MKPROFILE=no	# No profiling library
MKPIC=	no	# No shared library
WARNS?=	1	# All possible warnings

.include <bsd.lib.mk>
