#	$Id: Makefile,v 1.1 2000/09/26 18:48:00 ragge Exp $
#
# Rkom backend library Makefile
#

LIB=	rkom
SRCS=	rkom_subr.c rkom_lyskom.c

MKLINT=	no	# No lint library
MKPROFILE=no	# No profiling library
MKPIC=	no	# No so shared library
WARNS?=	1	# All possible warnings

.include <bsd.lib.mk>
